---
version: "2"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - TZ=${TZ:-Europe/Moscow}
    volumes:
      - ./src/config:/config
      - ./src/transcode:/transcode
      - ./src/data:/data
    restart: unless-stopped